class FlagStatus:
    FLAGGED = 'FLAGGED'
    NOT_FLAGGED = 'NOT_FLAGGED'

    _ALL = (FLAGGED, NOT_FLAGGED)


class PostStatus:
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    ERROR = 'ERROR'
    ARCHIVED = 'ARCHIVED'
    DELETING = 'DELETING'

    _ALL = (PENDING, COMPLETED, ERROR, ARCHIVED, DELETING)
