#!/usr/bin/env bash

set -a
[ -f .env ] && . .env
set +a

[ -z "$S3_UPLOADS_BUCKET_NAME" ] && echo "Env var S3_UPLOADS_BUCKET_NAME must be defined" && exit 1

aws s3 rm "s3://$S3_UPLOADS_BUCKET_NAME" --recursive
