class MediaStatus:
    AWAITING_UPLOAD = 'AWAITING_UPLOAD'
    PROCESSING_UPLOAD = 'PROCESSING_UPLOAD'
    UPLOADED = 'UPLOADED'
    ERROR = 'ERROR'
    ARCHIVED = 'ARCHIVED'
    DELETING = 'DELETING'

    _ALL = (AWAITING_UPLOAD, PROCESSING_UPLOAD, UPLOADED, ERROR, ARCHIVED, DELETING)
