class GqlNotificationType:
    USER_CHATS_WITH_UNVIEWED_MESSAGES_COUNT_CHANGED = 'USER_CHATS_WITH_UNVIEWED_MESSAGES_COUNT_CHANGED'
    USER_FEED_POST_ADDED = 'USER_FEED_POST_ADDED'

    _ALL = (USER_CHATS_WITH_UNVIEWED_MESSAGES_COUNT_CHANGED, USER_FEED_POST_ADDED)
