name: Deploy to staging
on:
  push:
    branches:
      - develop

jobs:
  staging-deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Load cached directories
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          # node 14.17 doesn't play well with serverless https://stackoverflow.com/a/67624151
          node-version: 14.16.1

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6

      - name: Install packages real-lambda-layers
        run: yarn install
        working-directory: real-lambda-layers

      - name: Install packages real-main
        run: yarn install
        working-directory: real-main

      - name: Deploy real-lambda-layers
        run: yarn deploy --stage staging
        working-directory: real-lambda-layers
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy real-main
        run: yarn deploy --stage staging
        working-directory: real-main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
